In [ ]:
from pathlib import Path

Path().cwd()

In [6]:
entry = {
    "hash": 1234,
    "name": "bob",
    "message": "hi", 
    "tag": "raw"
}
name = "new"
message = "hello"
tag = "intermediate"

msg = (
    "This data already exists in .datashelf under a different tag with the following metadata:\n\n"
    f"\t- Hash: {entry['hash']}\n\t- Name: {entry['name']}\n\t- Message: {entry['message']}\n\t- Tag: {entry['tag']}\n\n"
    "Would you like to update the metadata of this entry with the following metadata? (Y/N)\n\n"
    f"\t- New Name: {name}\n\t- New Message: {message}\n\t- New Tag: {tag}\n"
)
#response = input(msg)

print(msg)

This data already exists in .datashelf under a different tag with the following metadata:

	- Hash: 1234
	- Name: bob
	- Message: hi
	- Tag: raw

Would you like to update the metadata of this entry with the following metadata? (Y/N)

	- New Name: new
	- New Message: hello
	- New Tag: intermediate

In [1]:
from datetime import datetime
str(datetime.now())

'2026-03-10 18:22:16.541778'

In [2]:
datetime.now().replace(microsecond=0).isoformat()

'2026-03-10T18:22:19'

In [4]:
from datashelf.commands import init

In [5]:
init.init()

Datasehlf already initialized at /Users/rohankrishnan/Documents/GitHub/datashelf/.datashelf

In [ ]:
while (line := input("Enter text: ")) != "":
    print(f"You typed: {line}")

In [ ]:
line = " "
while line != "":
    line = input("Enter text: ")
    print(f"You typed: {line}")

In [ ]:
import shutil
shutil.copy2(".datashelf/metadata.json", ".datashelf/new.json")

In [ ]:
import json
with open(".datashelf/metadata.json", "r") as f:
    content = json.load(f)
    
content

In [ ]:
from pathlib import Path

def print_tree(path, prefix=''):
    """Prints a visual directory tree structure starting from the given path."""
    if path.is_file():
        print(f'{prefix}├── {path.name}')
        return

    # Handle directories
    print(f'{prefix}├── {path.name}/')
    # Get sorted list of all items (files and dirs)
    contents = sorted(list(path.iterdir()))
    # Iterate over contents and recursively call print_tree for subdirectories
    for item in contents:
        print_tree(item, prefix + '│   ')

# Example usage:
start_dir = Path('./datashelf') # You can change '.' to any specific path
print_tree(start_dir)

In [1]:
import pandas as pd

df = pd.read_csv("./customers-100.csv")

In [7]:
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [11]:
df_filtered = df[df["Subscription Date"] < "2020-08-24"]

In [12]:
df_filtered

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
22,23,2FB0FAA1d429421,Colleen,Howard,Greer and Sons,Brittanyview,Paraguay,1935085151,(947)115-7711x5488,rsingleton@ryan-cherry.com,2020-08-19,http://paul.biz/
28,29,3B5dAAFA41AFa22,Stefanie,Fitzpatrick,Santana-Duran,Acevedoville,Saint Vincent and the Grenadines,(752)776-3286,+1-472-021-4814x85074,wterrell@clark.com,2020-07-30,https://meyers.com/
29,30,EDA69ca7a6e96a2,Kent,Bradshaw,Sawyer PLC,North Harold,Tanzania,+1-472-143-5037x884,126.922.6153,qjimenez@boyd.com,2020-04-26,http://maynard-ho.com/
45,46,fD780ED8dbEae7B,Joanne,Montes,"Price, Sexton and Mcdaniel",Gwendolynview,Palau,(897)726-7952,(467)886-9467x5721,juan80@henson.net,2020-07-01,http://ochoa.com/
46,47,300A40d3ce24bBA,Geoffrey,Guzman,Short-Wiggins,Zimmermanland,Uzbekistan,975.235.8921x269,(983)188-6873,bauercrystal@gay.com,2020-04-23,https://decker-kline.com/
55,56,C6F2Fc6a7948a4e,Ralph,Haas,Montes PLC,Lake Ellenchester,Palestinian Territory,2239271999,001-962-434-0867x649,goodmancesar@figueroa.biz,2020-05-25,http://may.com/
60,61,a940cE42e035F28,Lynn,Pham,"Brennan, Camacho and Tapia",East Pennyshire,Portugal,846.468.6834x611,001-248-691-0006,mpham@rios-guzman.com,2020-08-21,https://www.murphy.com/
66,67,2A13F74EAa7DA6c,Makayla,Cannon,Henderson Inc,Georgeport,New Caledonia,001-215-801-6392x46009,027-609-6460,scottcurtis@hurley.biz,2020-01-20,http://www.velazquez.net/
67,68,a014Ec1b9FccC1E,Tom,Alvarado,Donaldson-Dougherty,South Sophiaberg,Kiribati,(585)606-2980x2258,730-797-3594x5614,nicholsonnina@montgomery.info,2020-08-18,http://odom-massey.com/
69,70,CC68FD1D3Bbbf22,Riley,Good,Wade PLC,Erikaville,Canada,6977745822,855-436-7641,alex06@galloway.com,2020-02-03,http://conway.org/
71,72,Ef859092FbEcC07,Richard,Roth,Conway-Mcbride,New Jasmineshire,Morocco,581-440-6539,9857827463,aharper@maddox-townsend.org,2020-02-23,https://www.brooks.com/
72,73,F560f2d3cDFb618,Candice,Keller,Huynh and Sons,East Summerstad,Zimbabwe,001-927-965-8550x92406,001-243-038-4271x53076,buckleycory@odonnell.net,2020-08-22,https://www.lucero.com/
73,74,A3F76Be153Df4a3,Anita,Benson,Parrish Ltd,Skinnerport,Russian Federation,874.617.5668x69878,(399)820-6418x0071,angie04@oconnell.com,2020-02-09,http://oconnor.com/
75,76,d40e89dCade7b2F,Debra,Riddle,"Chang, Aguirre and Leblanc",Colinhaven,United States Virgin Islands,+1-768-182-6014x14336,(303)961-4491,shieldskerry@robles.com,2020-07-11,http://kaiser.info/
78,79,CbAE1d1e9a8dCb1,Laurie,Pennington,"Sanchez, Marsh and Hale",Port Katherineville,Dominica,007.155.3406x553,+1-809-862-5566x277,cookejill@powell.com,2020-06-08,http://www.hebert.com/
84,85,03A1E62ADdeb31c,Corey,Holt,"Mcdonald, Bird and Ramirez",New Glenda,Fiji,001-439-242-4986x7918,3162708934,maurice46@morgan.com,2020-02-18,http://www.watson.com/
86,87,ebe77E5Bf9476CE,Duane,Woods,Montoya-Miller,Lyonsberg,Maldives,(636)544-7783x7288,(203)287-1003x5932,kmercer@wagner.com,2020-07-21,http://murray.org/
90,91,5ef6d3eefdD43bE,Nina,Chavez,Byrd-Campbell,Cassidychester,Bhutan,053-344-3205,+1-330-920-5422x571,elliserica@frank.com,2020-03-26,https://www.pugh.com/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [2]:
df.to_parquet("./customers-100.parquet", engine = "fastparquet")

In [13]:
df_filtered.to_parquet("./customers-100-filtered.parquet", engine = "fastparquet")

In [3]:
from datashelf.core.hashing import hash_parquet

In [15]:
from pathlib import Path
path = Path("./customers-100.parquet")
res = hash_parquet(path)
path_filtered = Path("./customers-100-filtered.parquet")
res_filtered = hash_parquet(path_filtered)
print(f"Hash of original dataset: {res}\nHash of filtered dataset: {res_filtered}")

Hash of original dataset: 27762c8bca5e8fccf814985a48221afced70e41f15ef72be533d429d94ad1999
Hash of filtered dataset: 9d016ba002b7155dfbcb36fc64b0e2209cd94ec2833e4353d24aefd94202b54d

In [16]:
path.suffix

'.parquet'

In [17]:
path.resolve()

PosixPath('/Users/rohankrishnan/Documents/GitHub/datashelf/customers-100.parquet')

In [ ]:
def add_three_numbers(a, b , c):
    first_two = a + b
    last = c + first_two
    print(last)
    
add_three_numbers(3,4,7,9)

TypeError: add_three_numbers() takes 3 positional arguments but 4 were given

In [22]:
add_three_numbers("three", "four", "five")

fivethreefour

In [23]:
a = {
    "HI":1,
    "hello":2
}

for i in a:
    print(i)

HI
hello

In [27]:
Path.cwd().expanduser()

PosixPath('/Users/rohankrishnan/Documents/GitHub/datashelf')

In [32]:
Path("./customers-100.csv").resolve()

PosixPath('/Users/rohankrishnan/Documents/GitHub/datashelf/customers-100.csv')

In [5]:
from datashelf import init, save, load

In [6]:
init.init()

In [7]:
save.save(data = "customers-100.csv", name = "customers_100_data", message = "Raw data for first 100 customers", tag = "raw")

Successfully saved 'customers_100_data' with hash 7e258d18.

In [8]:
save.save(data = "customers-100.csv", name = "customers_100_data", message = "External data from sales team for first 100 customers.", tag = "external")

Updated metadata for existing artifact 7e258d18.

In [9]:
save.save(data = "customers-100.csv", name = "customers_100_data", message = "External data from sales team for first 100 customers.", tag = "invalid-tag")

ValueError: Tag must be one of raw, external, intermediate, processed

In [10]:
save.save(data = "customers-100.parquet", name = "customers_100_data", message = "Same as CSV but parquet file", tag = "external")

Data customers_100_data already exists in .datashelf with hash 7e258d18b14409b97dbac4aea199038311a98bfc1cf94079766fc9df24c8dfff.

In [11]:
# test new data
save.save(data = "customers-100-filtered.parquet", name = "filtered_customers_100", message = "Filtered data", tag = "intermediate")

Successfully saved 'filtered_customers_100' with hash a1547f04.

In [12]:
# Test data outside of project root
save.save(data = "/Users/rohankrishnan/Downloads/online_retail.xlsx",
          name = "online_retail",
          message = "online retail dataset",
          tag = "external")

Successfully saved 'online_retail' with hash 79d3bd84.

In [15]:
load.load(lookup_key="7e258d18b") == load.load(lookup_key = "customers_100_data")

True

In [ ]:
from datashelf import inspect

inspect.ls()

Hash      Name                    Tag           Message
------------------------------------------------------------------------------------------------------------
0ecc1860  DataShelf Config                      This file holds basic configuration settings for DataShelf.
7e258d18  customers_100_data      external      External data from sales team for first 100 customers.
a1547f04  filtered_customers_100  intermediate  Filtered data
79d3bd84  online_retail           external      online retail datasetonline retail datasetonline retail d...

In [1]:
from datashelf.core.metadata import load_metadata
from datashelf.core.directory import find_datashelf_path
from datashelf.inspect import _create_metadata_entry_str

ds_path = find_datashelf_path()
meta = load_metadata(datashelf_path=ds_path)

msg = _create_metadata_entry_str(entry = meta["files"][1])

In [2]:
print(msg)

-------------------------------------------------------------------------------------------
Hash       7e258d18b14409b97dbac4aea199038311a98bfc1cf94079766fc9df24c8dfff
Name       customers_100_data
Tag        external
Message    External data from sales team for first 100 customers.
Stored at  artifacts/7e258d18b14409b97dbac4aea199038311a98bfc1cf94079766fc9df24c8dfff.parquet
Added      2026-03-12T05:04:48
----------------------------------------------------------------------------------------------------